### ISSUE TITLE
cannot find module 'is-buffer' in version 13.x.x (works in 12.0.2)

### ISSUE THREAD

**Issue by the-simian** [substack/node-browserify#1483]
Hello, upgrading to browserify 13.x.x, I came across an error when I tried to use it:   

```
Error: Cannot find module 'is-buffer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jesse\Desktop\ad-rabbit\node_modules\is-number\node_modules\kind-of\index.js:1:78)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jesse\Desktop\ad-rabbit\node_modules\is-number\index.js:10:14)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Jesse\Desktop\ad-rabbit\node_modules\fill-range\index.js:11:16)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
```

I am using node v5.4.1 and npm 3.3.12

Reverting to 12.x.x make the problem go away. I looked into it on these issues and I see two issues that may very well be related: #1482  and #1476 , the one @feross was working on. looks like it was for a good reason: a sizable increase in speed.

If I have mistakenly associated my error with these issues, feel free to close this. I am mostly submitting the issue to see if anyone else has the problem, or there is something I need to know about buffers in the most current versions of node/browserify I am not aware of.

thanks very much for your time

**Comment by feross** [comment]
@the-simian I've seen this too. Do you by chance use the testing tool `zuul`?

**Comment by the-simian** [comment]
@feross No, I don't I use mocha and chai in this particular project. Do you suspect this error might be the result of some interaction with another dependency? Besides browserify, the others of note are react, stylus, postcss and lodash

**Comment by feross** [comment]
Possible, but I'm not sure yet.

**Comment by the-simian** [comment]
Ok, no problem. Let me know if there's anything further I can do to help. I won't be able to dig further into this myself for a few days. Also if anyone else gets this error, they can respond here and we can then start to ascertain if it is related to interaction with another module. In the meantime, 12.0.2 is working just fine. Thanks again!

**Comment by feross** [comment]
This is still an issue. Here's a test run that demonstrates the problem: https://travis-ci.org/feross/parse-torrent/builds/116466564

**Comment by feross** [comment]
Maybe zuul is screwing with the `cwd` in a way that is confusing `insert-module-globals`?
