### ISSUE TITLE
Error in 9.0.6+ seems related to readonly streams

### ISSUE THREAD

**Issue by torarvid** [substack/node-browserify#1199]
Hey. We use browserify via gulp to build a libs.js containing all our 3rd party deps. This works fine in 9.0.4, but in 9.0.6 and 9.0.7 I get:

    _stream_readable.js:524
        var ret = dest.write(chunk);
                       ^
    TypeError: undefined is not a function
        at Producer.ondata (_stream_readable.js:524:20)
        at emitOne (events.js:77:13)
        at Producer.emit (events.js:166:7)
        at Producer.Readable.read (_stream_readable.js:356:10)
        at flow (_stream_readable.js:734:26)
        at resume_ (_stream_readable.js:714:3)
        at _stream_readable.js:701:7
        at process._tickDomainCallback (node.js:366:13)

**Comment by terinjokes** [comment]
This was an error in the gulp recipes that relied on internal behavior. (See #1191 and #1044). Please see the updated gulp guides:

* [Browserify + Uglify2](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-uglify-sourcemap.md#browserify--uglify2-with-sourcemaps)
* [Browserify + Globs](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-with-globs.md#browserify--globs)

You may also wish to consider using the Browserify API directly, and forgoing gulp entirely.

**Comment by spicydonuts** [comment]
> You may also wish to consider using the Browserify API directly, and forgoing gulp entirely.

Why might one want to consider doing that?

**Comment by terinjokes** [comment]
> Why might one want to consider doing that?

Keeping things simple, and not having to deal with integrating with gulp.

**Comment by spicydonuts** [comment]
Less work for sure, but I don't think people are setting up gulp for fun.
