### ISSUE TITLE
Resolving dependencies

### ISSUE THREAD

**Issue by Phoscur** [substack/node-browserify#97]
I don't get browserify to work on Windows7 x64, node 0.6.1

Possibly related: https://github.com/substack/node-browserify/issues/83

<code>
| project folder: server.js (running browserify as middleware)
|__
|    | .node_modules (e.g. underscore)
|__
.    | helpers (require underscore)

browserify("module.js", {require: ["underscore"], watch: true}) 
</code>

I require it already, why am I getting this error?:

<code>
Error: Cannot find module "underscore" from directory "d:\\myModule\\helpers"
    at EventEmitter.require (d:\myModule\node_modules\browserify\lib\wrap.js:352:19)
    at d:\myModule\node_modules\browserify\lib\wrap.js:430:14
    at Array.forEach (native)
.......
</code>

I don't want to leave a copy of underscore in each of my subfolders (like the helpers folder). There are ways around it, but I don't like to go them. I would really like to use browserify, but atm it's not working for me.

Is this windows related (path resolving)?
