### ISSUE TITLE
gulp + vinyl-transform + browserify - broken, last working 9.0.4

### ISSUE THREAD

**Issue by Kruegs** [substack/node-browserify#1217]
Hello!

I've been getting the below error since upgrading beyond 9.0.4.  I've also included my code for the gulp task further below.  It works with version 9.0.4.

I appreciate any help,
John

```
[17:16:46] Starting 'browserify'...
_stream_readable.js:540
    var ret = dest.write(chunk);
                   ^
TypeError: undefined is not a function
    at Producer.ondata (_stream_readable.js:540:20)
    at Producer.emit (events.js:107:17)
    at Producer.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

```
gulp.task("browserify", function() {
    var browserify     = require("browserify");
    var vinylTransform = require("vinyl-transform");

    var buildBundle = function () {
        return vinylTransform(function (filename) {
            var b = browserify(filename);
            return b.bundle();
        });
    };

    return gulp.src("src/js/*.js")
        .pipe(buildBundle())
        .pipe(gulp.dest("target/js"));
});
```

**Comment by terinjokes** [comment]
This was an error in the gulp recipes that relied on internal behavior. (See #1191 and #1044). Please see the updated gulp guides:

* [Browserify + Uglify2](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-uglify-sourcemap.md#browserify--uglify2-with-sourcemaps)
* [Browserify + Globs](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-with-globs.md#browserify--globs)
